server:
  servlet-path: /*
  port: 9002
  ssl:
    enabled: true
    key-password: changeit
    key-store-password: changeit
    key-store: classpath:_wildcard.transglobe.com.tw+5.p12
    key-store-type: PKCS12
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
fido:
  url:  https://tws-fido.wisecure-tech.com:8443
  headers:
    rp_domain_id: 1
    Protocol: FIDO2_0